# Generated by Django 2.2.6 on 2019-11-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flashcard',
            name='word_in_deck_uniq',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='word',
            new_name='phrase',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='meaning_id',
            field=models.CharField(default='xxx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.UniqueConstraint(fields=('deck', 'phrase'), name='phrase_in_deck_uniq'),
        ),
    ]
