# Generated by Django 2.2.6 on 2019-11-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20191111_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(condition=models.Q(default=True), fields=('user', 'default'), name='deck_default_per_user_uniq'),
        ),
    ]
